#+STARTUP: indent
#+MACRO: HS /Hōdo Station/
#+LATEX_CLASS: koma-article
#+LATEX_HEADER: \usepackage{spkb-pack}
#+LATEX_HEADER: \addbibresource{/Users/spkb/Documents/Bibliographies/mybib.bib}
#+OPTIONS: toc:nil
#+COLUMNS: %25ITEM %TARGET %ACTUAL %PRIORITY
#+TITLE: Press Freedom in Japan

* Front Matter :noexport:
#+BEGIN: columnview :hlines 1 :id global 
| ITEM                                        | TARGET | ACTUAL | PRIORITY |
|---------------------------------------------+--------+--------+----------|
| * Front Matter                              |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Press Freedom in Japan                    |    400 |    173 | B        |
| ** Dependence and Independence              |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Real world effects?                       |    400 |    307 | B        |
| ** Kishii Shigetada dropped from /News 23/? |        |        | B        |
| ** Furutachi - /News23/ caster replaced     |        |        | B        |
| ** 'Close Up Gendai'                        |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * A timeline of events                      |   1500 |    954 | B        |
| ** /Tsubaki Hatsugen Jiken/ (1993-4)        |        |        | B        |
| ** 2011.3 - Tsunami - Fukushima             |        |        | B        |
| ** Informal meetings increase               |        |        | B        |
| ** Momii - NHK                              |        |        | B        |
| ** Koga Shigeaki                            |        |        | B        |
| ** Pre-election letter to press             |        |        | B        |
| ** Furutachi goes                           |        |        | B        |
| ** Takaichi 'gyōmu teishi' threat           |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Issues                                    |    800 |    270 | B        |
| ** Nuclear Power                            |        |        | B        |
| ** Secrets Law                              |        |        | B        |
| ** War Law                                  |        |        | B        |
| ** General Election                         |        |        | B        |
| ** Abenomics                                |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Government people involved                |    800 |    782 | B        |
| ** Abe Shinzō                               |        |        | B        |
| ** Takaichi Sanae                           |        |        | B        |
| ** Suga Yoshihide                           |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Industry responsibility                   |    500 |    312 | B        |
| ** Adversarial Approach                     |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Discussion                                |    800 |    229 | B        |
| ** Journalistic Education                   |        |        | B        |
| ** Unions and other Associations            |        |        | B        |
| ** Identity and Ideology                    |        |        | B        |
|---------------------------------------------+--------+--------+----------|
| * Conclusions                               |    500 |      0 | B        |
|---------------------------------------------+--------+--------+----------|
| * TOTALS                                    |   5700 |   3027 | B        |
#+TBLFM: @>$2=vsum(@2$2..@>>$2)::@>$3=vsum(@2$3..@>>$3)
#+END:

#+BEGIN_abstract
\noindent
This paper briefly outlines the background which over the last several years has led to concerns over the future of the ability of Japan's press to contribute usefully to its democracy. 
#+END_abstract

* Press Freedom in Japan
:PROPERTIES:
:TARGET: 400
:ACTUAL: 173
:END:
The aims of the law are as follows (Section 1, article 1)

#+BEGIN_QUOTE
第一章　総則
（目的）

第一条 　この法律は、次に掲げる原則に従つて、放送を公共の福祉に適合するように規律し、その健全な発達を図ることを目的とする。
一 　放送が国民に最大限に普及されて、その効用をもたらすことを保障すること。
二 　放送の不偏不党、真実及び自律を保障することによつて、放送による表現の自由を確保すること。
三 　放送に携わる者の職責を明らかにすることによつて、放送が健全な民主主義の発達に資するようにすること。
#+END_QUOTE

Roughly speaking the aims of the law are:

#+BEGIN_QUOTE
1. To ensure that broadcasting is available to as many people as possible.
2. By guaranteeing the impartiality, veracity and independence of broadcasting, secure freedom of expression through broadcasting.
3. By clarifying the duties of those involved in boadcasting, to ensure that broadcasting contributes to the development of healthy democracy. (author's translation)
#+END_QUOTE

To summarise, the Broadcast Law was conceived and created as a way of ensuring that the broadcast industry was independent - not beholden to any particular section of society, and was thus in a position to contribute to the development of postwar Japan as a democracy.


** Dependence and Independence
In Japan, being independent can equate to 'having nor friends' - for a society where belonging, ranking, explicitly structured social arrangments are the norm - independence is a scary and probably unwelcome state. It implies being cut off, adrift, without support and guidance.

* Real world effects?
:PROPERTIES:
:TARGET: 400
:ACTUAL: 307
:END:
Taken separately the incidents and occurrences can all be accounted for separately, however their co-occurrence has to be accounted for in some way. Why *these* incidents, why *now*? And what might be the effect on those who carry on working in the news media?

The effect seems to be exactly what a government determined to stifle media criticism might hope for 

#+BEGIN_QUOTE
A source close to NHK sighed and said there is a growing atmosphere among NHK staff that they should be second-guessing the administration’s expectations.
#+END_QUOTE
SOURCE: [[http://www.japantimes.co.jp/news/2016/01/26/national/media-national/self-censorship-sensed-japans-tv-stations-replace-outspoken-anchors/#.Vzcfx2NE8eg][Self-censorship sensed as Japan's TV stations replace outspoken anchors | The Japan Times]]

** Kishii Shigetada dropped from /News 23/?
TBS evening news presenter dropped April 2016. 
#+BEGIN_QUOTE
Kishii expressed opposition to contentious security bills before they cleared the Diet last September and called on fellow opponents to speak up.
“Voices should continuously be raised (for the bills) to be scrapped,” he declared.
Criticism was heaped upon him, particularly from the right. One conservative political group said his statement violated the Broadcast Law, which states broadcasters must be politically impartial.
#+END_QUOTE
SOURCE: [[http://www.japantimes.co.jp/news/2016/01/26/national/media-national/self-censorship-sensed-japans-tv-stations-replace-outspoken-anchors/#.Vzcfx2NE8eg][Self-censorship sensed as Japan's TV stations replace outspoken anchors | The Japan Times]]
** Furutachi - /News23/ caster replaced
- despite on-air disagreement with Koga
** 'Close Up Gendai'
- caster replaced, program changed... Dave Spector!!!

An increase in the degree to which those within the mass media who take the idea of independence seriously - who realise how essential such a media is to a  functioning democracy - think it is necessary to bring the topic of 'political pressure' out for discussion.
* A timeline of events
:PROPERTIES:
:TARGET: 1500
:ACTUAL: 954
:END:
There are independent justifications and explanations for all the events looked at her, and indeed, within the mass media industries there will be many individuals for whom political pressure does not seem to be a relevant issue. While editorial staff in the mass media are the most visible and most vocal section, they are not the most numerous. Yet they the editorial staff in some sense *are* the mass media in that they are the people who fulfill its primary function of gathering, editing and presenting the information which allows audiences to (theoretically at least) participate as citizens.

** /Tsubaki Hatsugen Jiken/ (1993-4)
This well-documented incident\cite{Berger:1995} can be thought of as a turning point in government attitudes to the import of the Broadcast Law.(cite!) What had between its creation in 1950 and this point had been seen as a set of 'ethical guidelines' (/rinri-kijun/) for those in the mass media started to take on aspects of ???. It was from this point on that /gyōsei-shidō/ started to be used to deal with perceived infractions.
** 2011.3 - Tsunami - Fukushima
The Tohoku Quake/Tsunami and Fukushima Daiichi Nuclear Plant disasters of March 2011 marked another significant event in the downward spiral of press freedom in Japan. The veils of secrecy and impulse to obfuscation of the various sources of information - central government, Tokyo Power (TEPCO) and the selection nuclear industry related bodies referred to in Japanese as 'genpatsu-mura' (the nuclear village) all demonstrated the instinct to cover up and prevaricate in situations where openness, information and knowledge-sharing would have probably led to preferable outcomes for many concerned, particularly those people directly affected by this medley of disasters.

Reporters Sans Frontieres cites official attitudes to reporting of these matters as a primary concern in its report of 2012? when Japan's ranking fell from ??? to ???.

** Informal meetings increase

As the figures (see [[tab:meetings]])detailed by ??? in HSR 260 (p22), there are significant and regular contacts between members of the government and senior members of the press.

#+CAPTION: Number of meetings and one-to-ne interviews between PM Abe and media groupings during the 2nd and 3rd Abe cabinets (201?--present). p22, Hoso Report 260s
#+NAME: tab:meetings
| Media Group   | 1-to-1 ivs | Number of meetings |
|---------------+------------+--------------------|
| Yomiuri-NTV   | 30         | apx40              |
| Fuji-Sankei   | 30         | apx20              |
| Mainichi-TBS  | - [fn:1]   | apx10              |
| Asahi-TVAsahi | - [fn:1]   | 7                  |

[fn:1]: all other media groups total apx. 10.

# /One-on-one interviews w Abe/
# Fuji-Sankei - 30\
# Yomi-NTV - 30\
# Others - apx 10\
# (Source - p22, Hoso Report 260s)

It can be seen from these figures that not all media groupings are treated the same way by the government. Those generally seen as more conservative[CITE], with views that generally align fairly well with the views of an LDP cabinet can be seen to have been favoured with access to PM Abe.
** Momii - NHK
Katsuto Momii, in places described as a friend of Shinzo Abe, was appointed Chairman of NHK in ??? His first official act was to effectively undermine the standing of the organisation he was heading by making inflammatory comments on the 'comfort women' issue. He soon followed this up with further statements which seemed to suggest that under his leadership NHK would be following the government line.
#+BEGIN_QUOTE
"it would not do for us to say 'left' when the government is saying 'right',"
#+END_QUOTE
SOURCE: [[mac-evernote:x-coredata://BEC16A4F-B349-47C5-B13D-8D5CA07C067B/ENNote/p1419][Abe Should Condemn NHK Officials' Comments: U.S. Paper]]

** Koga Shigeaki
TV Asahi's Tsubaki ?? was perhaps the cause of government attitudes to use of the Broadcast Law as a means of control over broadcasters. TV Asahi's regular evening news program, Nyūsu Station/Hōdō Station has likewise proved to be a fairly regular thorn in the side government. The latest manifestation of this antipathy - perhaps applying to Abe and the whole Asahi media group (Asahi Shimbun and TV Asahi) was the dramatic removal/career suicide of regular contributor and commentator Shigeaki Koga in April 2015. 

Koga, formerly a government official <CHECK> had been a regular commentator on /Hōdō Station/ since ??? On the ??<date> of the show he took the presented off-guard and departed from the agreed script to air his view that he had been hounded from the show by 'bashing' from the Cabinet Office. He later held up a 'flip' (hand-held printed sheet used to display graphics on Japanese television) printed with the words "I am not Abe", echoing the "I am Charlie" meme of previous weeks.

** Pre-election letter to press
In the run-up to the General House of Representatives election of 14 Dec 2014, the LDP/government thought it expedient to send broadcasters a letter reminding them to make sure to be 'fair' in their coverage. As Shigeaki Koga explains:
#+BEGIN_QUOTE
“Years ago, producers would have probably ripped up a letter like that and thrown it in the bin, but in this case they copied it and sent it to their news departments,”
#+END_QUOTE
[[mac-evernote:x-coredata://BEC16A4F-B349-47C5-B13D-8D5CA07C067B/ENNote/p1797][Japanese media facing political pressure, says Abe critic]]

The perceived risk of upsetting the Abe government -- and where this risk might bring on repercussions became clear early in 2016?? -- meant that instead of the recipients being up front about an attempt by politicians to influence the nature of their coverage, by revealing the letter and its contents to their viewers and asking for an explanation from its originators, they decided to keep it an internal matter and indeed passed the threat on down the chain of management to those in a position to actually affect content.<CHECK>

** Furutachi goes
Perhaps triggered by his 'failure to control' his guest regular commentator Koga, ??? Furutachi presented hia last edition of the TV Asahi evening news show {{{HS}}} on <DATE>. He had originally taken over the show, employed as an outside presenter (he works for his own production company, ???)m from the previous presenter and lead newscaster Kume Hiroshi, a similarly outspoken individual. {{{HS}}} since it went on-air (as /News Station/ww) in 1985? had gained a reputation for being willing to deal with stories which would ruffle government and establishment feathers. There have been occasions when fervour got the better of news judgment but on the whole, the has played a vital role in re-invigorating broadcast news in Japan. 

Since Furutachi's departure his role has been taken by ???, a TV Asahi employee; whether the show will retain its slightly maverick approach, now that the lead newscaster is also a corporate employee rather than a freelance, is a matter that should concern those who understand the importance of the role of a program like {{{HS}}}.
** Takaichi 'gyōmu teishi' threat

* Issues
:PROPERTIES:
:TARGET: 800
:ACTUAL: 270
:END:
** Nuclear Power

3/14 Asahi paper, then /shasetsu/ 4/15 - complaints from Matsuura Nuclear Kisei-cho saying article wrong. 16/3/16 govt complained at regular presser.

Hokkaido Paper - Uede reporter
** Secrets Law
This refers to the /Tokutei Himitsu Hogo Hō/ passed by the Diet on ??? in the face of a great deal of concern from civil society groups and opposition politicians.
** War Law
One of the most divisive issues that Japanese society is dealing with today, involving as it does debates about Japan's wartime activities, the nature of its constitution and a questioning of the 'peace state' identity that has been carefully constructed since
** General Election

- Letter from LDP/government reminding broadcasters to be 'fair' - look at exact usage of words - /chūritsu/ and /kōhei/.

See Kishii argument in HSReport.

As other have argued \citep[27--8]{Street:2011} the positions implied by the Japanese term /chūritsu/, while it might seem desirable, can be seen on a fairly cursory inspection to be far from practicably useful or desirable. The term, in Japanese is made up of two characters, /chū/ meaning, center or middle, and /ritsu/ meaning 'to stand, standing' - it implies just this - taking up a central position. The question thus becomes, how does the press know or judge where this 'central' position is? And, is this a suitable position for the press?

Ultimately, is it healthy for a society to have a media which can be dragged left and right with the vagaries of changes in the political landscape? Surely this is the opposite of a principled press. 3
# insert citations here - Street?

Is /chūritsu/ equivalent to 'balance'?

** Abenomics

* Government people involved
:PROPERTIES:
:TARGET: 800
:ACTUAL: 782
:END:
** Abe Shinzō
Two-time prime minister(2006--7, 2012--6)!!, grandson of former PM(1957-1960) Nobusuke Kishi, son of ex-/Mainichi Shimbun/ reporter, LDP foreign minister and faction leader, Shintaro Abe.

Deeply conservative.

Seems to be unusually insensitive to ruffling feathers, making use of a weak opposition to push through measures in some haste.

Economic policy largely a failure.

Main interests, if his book 'Utsukuishii Kuni he' (Toward a Beautiful Country) is anything to go by, are foreign policy and diplomacy. Japan's position in the world, particularly with regard to the US.

#+BEGIN_QUOTE
In his 232-page book, Abe made little mention of macroeconomic or financial policies.

He dedicated six of the seven chapters to his discussion on diplomacy, nationalism and education. The remaining one looks at the nation’s social security system and low birthrate.
#+END_QUOTE
Source: [[mac-evernote:x-coredata://BEC16A4F-B349-47C5-B13D-8D5CA07C067B/ENNote/p1807][Formed in childhood, roots of Abe's conservatism go deep | The Japan Times]]

And as the same article mentions he can be 'pragmatic' (unprincipled!) as demonstrated by his controlled use of nationalistic rhetoric and symbolism before the 200? election as a means to woo conservative voters which was then toned down when the practicalities of governing needed to be attended to. This is not a feature particular to Abe, Japanese politics is primarily a matter of power distribution and management, not one that encourages or rewards, or even expects, principled policy positions.
# add something from Curtis book!

** Takaichi Sanae
Takaichi Sanae first joined the government during Abe Shinzo's second cabinet when she was appointed Minister for Internal Affairs and communications in September 2014. At time of writing she is still in this role, being retained after the reshuffle of December 2014.
# 第2次安倍内閣改造内閣	高市　早苗
# 平成26年9月3日～平成26年12月24日
# 第3次安倍内閣	- 第3次安倍内閣改造内閣
# 平成26年12月24日～present

Shortly after her promotion it emerged she had met right-winger - the Guardian went as far as to say 'Neo-Nazi'(see [[mac-evernote:x-coredata://BEC16A4F-B349-47C5-B13D-8D5CA07C067B/ENNote/p620][Neo-Nazi photos pose headache for Shinzo Abe | World news | theguardian.com]]) - Kazunari Yamada, and had consented to be photographed with him in front of the Japanese national flag, still a controversial symbol for many in Japan[CITE]. EG - [[http://abcnews.go.com/International/japanese-teachers-fight-flag-salute-national-anthem-enforcement/story?id=12909556][Japanese Teachers Fight Flag Salute, National Anthem Enforcement - ABC News]]

She had also voiced the belief that:
# the ruling Liberal Democratic Party’s own policy chief said on NHK the previous day
#+BEGIN_QUOTE
that President Shinzo Abe disagreed with the findings of the Tokyo War Crimes Tribunal.
#+END_QUOTE
SOURCE: [[mac-evernote:x-coredata://BEC16A4F-B349-47C5-B13D-8D5CA07C067B/ENNote/p422][Suga rushes to smother LDP's latest brush fire over war - The Japan Times]]

As politicians cannot fail to be aware, it is impossible to unsay things - despite the prevalence of the term /tekkai/ ('withdraw')  in the rhetoric of Japanese political apology. Once an utterance has been made it can be left to appeal to those who must be appealed to and winkingly 'retracted' for the sake of propriety. It requires little of, and would seem to involve little damage to credibility, for a politician to withdraw a statement if they can argue that they have done so under pressure from 'biased', 'left-wing' media.

** Suga Yoshihide
Suga Yoshihide was Vice-minister for Internal Affairs and communications during the third Koizumi cabinet, Nov 2005 - Sep 2006; he was then promoted to Minister when Abe took over the premiership in Sep 2006, a post he held until August 2007.

# Vice Soumu Min under Koizumi 3rd cab. (Takenaka)
# 菅　義偉	平成17年11月2日～平成18年9月26日
# Then Minister under succeeding Abe cab.
# 第1次安倍内閣	菅　義偉 総務大臣
# 平成18年9月26日～平成19年8月27日

Suga's role of /Kanbōchōkan/ - Chief Cabinet Secretary puts him in the position where he is the primary government spokesman, he regularly appears in the mass media making statements on government policy and reacting to events and comments made by others.

However, the unwritten rules of Japanese reporting mean that it is very rare for him to face 'hard' public questioning on matter of concern. Political reporting in Japan tends to be 'polite' to the point of unctuousness. Thus, when the presenter of NHK's daily current affairs show /Close-Up Gendai/ Hiroko Kuniya deviated from this norm and wrepeatedly asked if the newly agreed 'War Law' might not lead to Japan's becoming embroiled in allies' conflicts, he was a little put out.
# interview July 2014

Kuniya presented her last program on ??? after a career of 23 years at NHK.
* Industry responsibility
:PROPERTIES:
:TARGET: 500
:ACTUAL: 312
:END:

If the mass media industries, the individuals within them, themselves can't be bothered (or don't think it's a good idea) to push back against government encroachment, how can audiences ensure they get the information they think they need to live their lives? If the established mass media companies are going to abandon their role as watchdogs, it makes sense to turn elsewhere. This is what people will do.

Ultimately it is poor business for the mass media industries to give up on the one thing that gives them any social standing they might have; credibility. In a country like Japan, which has recent experience of free and un-free media, the sensitivity to governmemnt attempts to influence the content of mass media communication is high. And people are aware of what a government controlled media system looks and sounds like, also where it can lead.

It is entirely possible that there is a significant section of Japanese society which would welcome the return of the strong state, and a Japan ready to throw its weight about on the international stage.

The responsibility for this state of affairs goes beyond the institutions of the mass media itself; there is a profound dearth of journalistic education in Japan, thus very few places where any sort of professional identity can be learned and nurtured. Thus the first serious experience of journalism that reporters have is *within* the context of a specific company \citep{Cooper-Chen:1997a}. One of the essential dynamics of industrialised reporting - the tension between a 'vertical' company identity (and identification with company policy) and the broader 'horizontal' professional identity (and identification with its idealised standards) is lacking in Japan.

Simultaneous belonging to groups with conflicting interests (company vs profession) id perhaps more difficult in a country where (as near a possible) identity with the group and its is felt to be desirable.

** Adversarial Approach (lackings)

From: \citep{Oi:2012}

# Although the watchdog role is considered an important media function, only about one-third of Japanese journalists believe they actually fulfil this role

# ...about 6 out of 10 Japanese news professionals believe that the relationship between journalist  and government sources is 'very' 7% or 'somewhat' 58.4 % cooperative. Only a small minority rates this relationship as 'very' 1% or 'somewhat' 13.5 hostile. This suggests that most Japanese  journalists their relationship with government is symbiotic rather than antagonistic.

# Most journalists (82.9%) note that there is a clear need to improve journalism education and training in JAPAN . ... Journalism training in Japan remains unstructured, largely based upon on-the-job training or apprenticeships. (GAUNT 1992)

# The virtual absence of schools of journalism in Japan might be recognised a a serious problem (Oi 2009a, 2009b)

# Gaunt - making the newsmakers

# Oi 2009a/b - /Shintei Shimbun-gaku/, ed Hamada, Tajima, Katsura
# /Media kenkyu to Janarizumu/, eds Tsuganezawa
* Discussion
:PROPERTIES:
:TARGET: 800
:ACTUAL: 229
:END:
- Structural lack of agility
- Assumption of benevolence
- Lack of 'distance' / symbiosis
** Journalistic Education
The widely-used 'Shingaku.net' site returns just four hits for a search for the keyword 'janarizumu'. The universities offering courses are Chuo University, Senshu Daigaku, Waseda and the Wellness Sports Daigaku. Senshu offers a course in the 'Humanities and Journalism Department' (Jinbun Janarizumu Gakka) of its College of Literature[[http://shingakunet.com/gakko/SC000406/gakubugakka/][ 中央大学／募集学部・学科・コース一覧【リクナビ進学】]]. Chuo offers a cross-departmental Journalism Program which brings in faculty from Economics, Literature and Policy.[[http://www.chuo-u.ac.jp/aboutus/gp/flp/program/journalism/][ジャーナリズムプログラム | 中央大学]]. Waseda offers a course which includes journalism modules in the Creative Writing and Criticism program available in its School of Culture, Media and Society.[[https://www.waseda.jp/flas/cms/about/theoretical/cwc/][文芸・ジャーナリズム論系 – 早稲田大学 文化構想学部]].
There do not seem to be any dedicated schools or departments for the teaching of journalism.

Where do the people who will become journalists acquire a professional identity? If journalism is more akin to a shared ideology CITE-DEUZE!, where will this be learned? 

These seems to be little readon to suspect that there has been significant change since Cooper-Chen and Takeichi's (1997) overview of the differences between the US and Japanese routes into professional journalism written nearly 20 years ago \citep{Cooper-Chen:1997a}.

** Unions and other Associations
** Identity and Ideology
* Conclusions
:PROPERTIES:
:TARGET: 500
:ACTUAL: 0
:END:

#+BEGIN_LATEX
\printbibliography
#+END_LATEX

* TOTALS :noexport:
:PROPERTIES:
:TARGET: 
:ACTUAL: 
:END:

